name: 'Build CLI and attach to GitHub release'

on:
  release:
    types: [ published ]

  workflow_dispatch:

jobs:
  build:
    name: 'Build CLI and attach to GitHub release'
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Setup Go
      - name: 'Setup Go'
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      # Print Go version
      - run: go version

      # Build and release
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
