name: 'go'

on:
  release:
    types: [published]

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - name: 'Checkout'
        uses: actions/checkout@v3
      # Build Go binaries
      - name: 'Build Go binaries'
        uses: cloudposse/actions/go/build@0.15.0
        env:
          GO111MODULE: on
          # Architectures to build for
          GOX_OSARCH: >-
            darwin/386
            darwin/amd64
            darwin/arm64
            freebsd/386
            freebsd/amd64
            freebsd/arm
            linux/386
            linux/amd64
            linux/arm
            linux/arm64
            linux/s390x
            netbsd/386
            netbsd/amd64
            netbsd/arm
            openbsd/386
            openbsd/amd64
            windows/386
            windows/amd64
            windows/arm64
          OUTPUT_PATH: ${{ github.workspace }}/release/${{ github.event.repository.name }}_
      # Upload artifacts for this build
      - name: 'Upload artifacts'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
          path: ${{ github.workspace }}/release/*
      # Attach Go binaries to GitHub Release
      - name: 'Attach artifacts to GitHub Release'
        if: ${{ github.event_name == 'release' }}
        uses: cloudposse/actions/github/release-assets@0.31.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_PATH: ${{ github.workspace }}/release/${{ github.event.repository.name }}_*
